#!/bin/sh
# xxbuild [flags] [pkgs..] - build packages for a pre-defined set of archs

: "${XBPS_HOSTDIR:="$HOME/.cache/xxtools/hostdir"}"
: "${XBPS_MASTERDIR:="$(pwd)/masterdir.xxtools"}"
: "${XXBUILD_HOSTARCH_FOR_CROSS:="$(uname -m)"}"

cd "$(xdistdir)" || exit 1

can_build_natively_for_arch() {
	arch="$1"
	native=
	case "$(uname -m)" in
		x86_64)
			case "$arch" in
				i686* | x86_64*) native=y ;;
			esac
			;;
		aarch64)
			case "$arch" in
				armv7* | aarch64*) native=y ;;
			esac
			;;
	esac
	[ "$native" = "y" ] && return 0 || return 1
}

_xbps_src() {
	(
		set -x
		#shellcheck disable=SC2086
		./xbps-src $xbps_src_flags "$*"
	)
}

summary="$(printf '\n%s\n' "SUMMARY")"
append_summary() {
	pkg="$1"
	host_arch="$2"
	target_arch="$3"
	cross="$4"
	result="$5"
	summary="$(printf '%s\n' "$summary" "pkg:${pkg} host:${host_arch} target:${target_arch} cross:${cross} result:${result}")"
}

xbps_src_flags=
xxbuild_force=
xxbuild_keep_going=
for arg; do
	case "$arg" in
		-f) xxbuild_force=y ;;
		-k) # make build failure non-fatal
			xxbuild_keep_going=y
			shift
			continue
			;;
		-*) : ;;
		*) break ;;
	esac
	xbps_src_flags="$xbps_src_flags $arg"
	shift
done

if [ "$#" = "0" ]; then
	# if no packages are given, build changed templates commited on this branch
	rm -f /tmp/templates
	common/travis/changed_templates.sh &&
		set -- "$(cat /tmp/templates)"
fi

# ensure all templates exist
fail=
pkgs=
for pkg; do
	if [ -f "srcpkgs/$pkg/template" ]; then
		t="srcpkgs/$pkg/template"
	elif [ -f "$pkg/template" ]; then
		t="$pkg/template"
	elif [ -f "$pkg" ]; then
		t="$pkg"
	else
		printf 'FAIL: no template found for: %s\n' "$pkg" >&2
		fail=y
		continue
	fi
	pkgs="$pkgs $(printf '%s' "$t" | cut -d'/' -f2)"
done
[ -z "$fail" ] || exit 1
[ -n "$pkgs" ] || exit 1

#shellcheck disable=SC2086
printf 'Building: %s\n' $pkgs

mkdir -p "$XBPS_HOSTDIR" "$XBPS_MASTERDIR"
export XBPS_HOSTDIR
export XBPS_MASTERDIR

_xbps_src binary-bootstrap
_xbps_src clean
_xbps_src bootstrap-update

# clean binpkgs, to not spoil the result by reusing prebuilt packages
if [ -n "$xxbuild_force" ]; then
	rm -rf "$XBPS_HOSTDIR/binpkgs"
fi

bailout=
for arch in \
	"x86_64" "x86_64-musl" "i686" \
	"aarch64-musl" \
	"armv7l-musl" "armv6l-musl"; do

	if can_build_natively_for_arch "$arch"; then
		cross=n
		master_arch="$arch"
		xbps_src_cross_flags=
	else
		cross=y
		master_arch="${XXBUILD_HOSTARCH_FOR_CROSS:-"$(xbps-uhelper arch)"}"
		xbps_src_cross_flags="-a $arch"
	fi
	# rebuild masterdir for native archs
	if [ "$(cat "$XBPS_MASTERDIR/.xbps_chroot_init")" != "$master_arch" ]; then
		rm -rf "$XBPS_MASTERDIR"
		_xbps_src binary-bootstrap "$master_arch"
	fi

	# mimic xbulk, but check exit code to not fail on broken/nocross
	# `xbulk $xbps_src_flags -f $cross $(./xbps-src sort-dependencies $@)`
	for pkg in $(./xbps-src sort-dependencies "$pkgs"); do
		_xbps_src "$xbps_src_cross_flags" pkg "$pkg"
		ret=$?

		result=
		case "$ret" in
			0)
				result="OK"
				;;
			2) # nocross, broken or no match in `archs=`
				result="SKIPPED"
				;;
			*)
				result="FAILED"
				[ -n "$xxbuild_keep_going" ] || bailout=y
				;;
		esac
		append_summary "$pkg" "$master_arch" "$arch" "$cross" "$result"

		[ -z "$bailout" ] || break
	done
	[ -z "$bailout" ] || break
done

echo "$summary"
exit $ret
